# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank Trial',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('tank_trial_id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_trial_name', models.CharField(max_length=30, null=False, blank=False)),
                ('tank_trial_station_id', models.ForeignKey(to='campaign.Station',
                db_column='tank_trial_station_id', db_index=False, db_constraint=False)),
                ('tank_trial_height', models.CharField(max_length=15, null=False, blank=False)),
                ('tank_trial_material', models.CharField(max_length=15, null=False, blank=False)),
                ('tank_trial_replica', models.CharField(max_length=15, null=False, blank=False)),
                ('tank_trial_pump_level', models.CharField(max_length=15, null=False, blank=False)),
                ('tank_trial_date', models.DateTimeField(null=False, blank=False)),
                ('tank_trial_file_name', models.CharField(max_length=30, null=False, blank=False)),
                ('tank_trial_temp', models.FloatField(null=True, blank=True)),
                ('tank_trial_salt', models.FloatField(null=True, blank=True)),
                ('tank_trial_cond', models.FloatField(null=True, blank=True)),
                ('tank_trial_dox', models.FloatField(null=True, blank=True)),
                ('tank_trial_orp', models.FloatField(null=True, blank=True)),
                ('tank_trial_comments', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'laboratory"."tank_trial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tank Trial',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=30, null=False, blank=False)),
                ('sample_station_id', models.ForeignKey(to='campaign.Station',
                db_column='sample_station_id', db_index=False, db_constraint=False)),
                ('sample_deployment_date', models.DateTimeField(null=True, blank=True)),
                ('sample_recovery_date', models.DateTimeField(null=True, blank=True)),
                ('sample_impairment_date', models.DateTimeField(null=True, blank=True)),
                ('sample_height', models.CharField(max_length=15, null=False, blank=False)),
                ('sample_material', models.CharField(max_length=15, null=False, blank=False)),
                ('sample_replica', models.CharField(max_length=15, null=False, blank=False)),
                ('sample_file_name', models.CharField(max_length=30, null=True, blank=True)),
                ('sample_weight_pre_deployment', models.FloatField(null=True, blank=True)),
                ('sample_weight_post_recovery', models.FloatField(null=True, blank=True)),
                ('sample_comments', models.TextField(null=True, blank=True)),
                ('sample_image_deployment', models.ImageField(upload_to='sample_image_deployment', blank=True, null=True)),
                ('sample_image_recovery', models.ImageField(upload_to='sample_image_recovery', blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory"."sample',
                'managed': True,
            },
        ),

        migrations.RunSQL("ALTER TABLE laboratory.tank_trial ADD CONSTRAINT tank_trial_station_fk FOREIGN KEY(tank_trial_station_id) REFERENCES campaign.station(station_id)"),
        migrations.RunSQL("ALTER TABLE laboratory.sample ADD CONSTRAINT sample_station_fk FOREIGN KEY(sample_station_id) REFERENCES campaign.station(station_id)"),
        migrations.RunSQL("ALTER TABLE laboratory.tank_trial ADD CONSTRAINT tank_trial_name_unique UNIQUE(tank_trial_name)"),
        migrations.RunSQL("ALTER TABLE laboratory.sample ADD CONSTRAINT sample_name_unique UNIQUE(sample_name)"),]
