# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30, null=False, blank=False)),
                ('product_description', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'products"."product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_name', models.CharField(max_length=30, null=False, blank=False)),
                ('publication_date', models.DateTimeField(null=True, blank=True)),
                ('publication_citation', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'products"."publication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=30, null=False, blank=False)),
                ('staff_surname', models.CharField(max_length=30, null=False, blank=False)),
                ('staff_position', models.CharField(max_length=30, null=True, blank=True)),
                ('staff_email', models.CharField(max_length=30, null=True, blank=True)),
            ],
            options={
                'db_table': 'products"."staff',
                'managed': True,
            },
        ),
        migrations.RunSQL("ALTER TABLE products.product ADD CONSTRAINT product_name_unique UNIQUE(product_name)"),
        migrations.RunSQL("ALTER TABLE products.publication ADD CONSTRAINT publication_name_unique UNIQUE(publication_name)"),
        migrations.RunSQL("ALTER TABLE products.staff ADD CONSTRAINT staff_email_unique UNIQUE(staff_email)"),
        ]
