# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=True, blank=True)),
                ('updated_by_id', models.IntegerField(null=True, blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30, null=False, blank=False)),
                ('station_description', models.TextField(null=True, blank=True)),
                ('station_geospatial_lat', models.FloatField(null=True, blank=True)),
                ('station_geospatial_lon', models.FloatField(null=True, blank=True)),
                ('station_geospatial_lat_units', models.CharField(max_length=10,null=True, blank=True)),
                ('station_geospatial_lon_units', models.CharField(max_length=10,null=True, blank=True)),
                ('station_geospatial_datum', models.CharField(max_length=10,null=True, blank=True)),
            ],
            options={
                'db_table': 'campaign"."station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=True, blank=True)),
                ('updated_by_id', models.IntegerField(null=True, blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('cruise_id', models.AutoField(primary_key=True, serialize=False)),
                ('cruise_name', models.CharField(max_length=30, null=False, blank=False)),
                ('cruise_description', models.TextField(null=True, blank=True)),

            ],
            options={
                'db_table': 'campaign"."cruise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('instrument_id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(max_length=30, null=False, blank=False)),
                ('instrument_model', models.TextField(null=True, blank=True)),
                ('instrument_manufacturer', models.TextField(null=True, blank=True)),
                ('instrument_serial', models.TextField(null=True, blank=True)),
                ('instrument_description', models.TextField(null=True, blank=True)),
                ('instrument_type', models.CharField(max_length=15, null=True, blank=True)),
            ],
            options={
                'db_table': 'campaign"."instrument',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('created_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_by_id', models.IntegerField(null=False, blank=False)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('deployment_id', models.AutoField(primary_key=True, serialize=False)),
                ('deployment_cruise_id', models.ForeignKey(to='campaign.Cruise',
                db_column='deployment_cruise_id', db_index=False, db_constraint=False)),
                ('deployment_station_id', models.ForeignKey(to='campaign.Station',
                db_column='deployment_station_id', db_index=False, db_constraint=False)),
                ('deployment_instrument_id', models.ForeignKey(to='campaign.Instrument',
                db_column='deployment_instrument_id', db_index=False, db_constraint=False)),
                ('deployment_name', models.CharField(max_length=30, null=False, blank=False)),
                ('deployment_description', models.TextField(null=True, blank=True)),
                ('deployment_initial_date', models.DateTimeField(null=True, blank=True)),
                ('deployment_end_date', models.DateTimeField(null=True, blank=True)),
                ('deployment_filename', models.CharField(max_length=50, null=True, blank=True)),
                ('deployment_geospatial_lon_max', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lon_min', models.TextField(null=True, blank=True)),
                ('deployment_principal_investigator', models.TextField(null=True, blank=True)),
                ('deployment_project', models.TextField(null=True, blank=True)),
                ('deployment_principal_investigator_email', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lat_resolution', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lat_units', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lon_units', models.TextField(null=True, blank=True)),
                ('deployment_data_center', models.TextField(null=True, blank=True)),
                ('deployment_author_url', models.TextField(null=True, blank=True)),
                ('deployment_distribution_statement', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lon_resolution', models.TextField(null=True, blank=True)),
                ('deployment_acknowledgement', models.TextField(null=True, blank=True)),
                ('deployment_code', models.TextField(null=True, blank=True)),
                ('deployment_publisher_name', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_vertical_max', models.TextField(null=True, blank=True)),
                ('deployment_author_email', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_vertical_units', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_vertical_min', models.TextField(null=True, blank=True)),
                ('deployment_local_time_zone', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_vertical_resolution', models.TextField(null=True, blank=True)),
                ('deployment_license', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lat_min', models.TextField(null=True, blank=True)),
                ('deployment_geospatial_lat_max', models.TextField(null=True, blank=True)),
                ('deployment_contributor_name', models.TextField(null=True, blank=True)),
                ('deployment_contributor_role', models.TextField(null=True, blank=True)),
                ('deployment_institution', models.TextField(null=True, blank=True)),
                ('deployment_publisher_url', models.TextField(null=True, blank=True)),
                ('deployment_citation', models.TextField(null=True, blank=True)),
                ('deployment_publisher_email', models.TextField(null=True, blank=True)),
                ('deployment_author', models.TextField(null=True, blank=True)),
                ('deployment_area', models.TextField(null=True, blank=True)),
                ('deployment_data_center_email', models.TextField(null=True, blank=True)),
                ('geospatialverticalpositive', models.TextField(null=True, blank=True)),
            ],
            options={
                'db_table': 'campaign"."deployment',
                'managed': True,
            },
        ),

        migrations.RunSQL("ALTER TABLE campaign.deployment ADD CONSTRAINT deployment_cruise_fk FOREIGN KEY(deployment_cruise_id) REFERENCES campaign.cruise(cruise_id)"),
        migrations.RunSQL("ALTER TABLE campaign.deployment ADD CONSTRAINT deployment_instrument_fk FOREIGN KEY(deployment_instrument_id) REFERENCES campaign.instrument(instrument_id)"),
        migrations.RunSQL("ALTER TABLE campaign.deployment ADD CONSTRAINT deployment_station_fk FOREIGN KEY(deployment_station_id) REFERENCES campaign.station(station_id)"),
        migrations.RunSQL("ALTER TABLE campaign.cruise ADD CONSTRAINT cruise_name_unique UNIQUE(cruise_name)"),
        migrations.RunSQL("ALTER TABLE campaign.deployment ADD CONSTRAINT deployment_name_unique UNIQUE(deployment_name)"),
        migrations.RunSQL("ALTER TABLE campaign.station ADD CONSTRAINT station_name_unique UNIQUE(station_name)"),
        migrations.RunSQL("ALTER TABLE campaign.instrument ADD CONSTRAINT instrument_name_unique UNIQUE(instrument_name)"),
        ]
